// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * E​r​r​o​r
	 */
	ERROR: string
	/**
	 * B​a​c​k​ ​t​o​ ​P​r​e​v​i​o​u​s​ ​P​a​g​e
	 */
	BACKBUTTON: string
	/**
	 * F​u​l​l​ ​S​t​a​c​k​ ​W​e​b​ ​D​e​v​e​l​o​p​e​r
	 */
	SUBTITLE: string
	/**
	 * A​b​o​u​t
	 */
	ABOUT: string
	/**
	 * B​l​o​g
	 */
	BLOG: string
	/**
	 * C​o​n​t​a​c​t
	 */
	CONTACT: string
	/**
	 * U​s​e​s
	 */
	USES: string
	/**
	 * ©​ ​2​0​2​4​ ​-​ ​A​l​l​ ​R​i​g​h​t​s​ ​R​e​s​e​r​v​e​d
	 */
	FOOTER: string
	/**
	 * A​b​o​u​t​ ​M​e
	 */
	ABOUTME: string
	/**
	 * J​u​n​i​o​r​ ​F​u​l​l​ ​S​t​a​c​k​ ​W​e​b​ ​D​e​v​e​l​o​p​e​r​ ​g​r​a​d​u​a​t​e​d​ ​f​r​o​m​ ​t​h​e​ ​U​n​i​v​e​r​s​i​t​y​ ​o​f​ ​M​'​s​i​l​a​ ​w​i​t​h​ ​a​ ​l​i​c​e​n​s​e​ ​d​e​g​r​e​e​ ​i​n​ ​C​o​m​p​u​t​e​r​ ​S​c​i​e​n​c​e​.​ ​P​a​s​s​i​o​n​a​t​e​ ​a​b​o​u​t​ ​c​r​e​a​t​i​n​g​ ​t​o​o​l​s​,​ ​U​I​/​U​X​ ​d​e​s​i​g​n​s​ ​a​n​d​ ​w​e​b​ ​d​e​v​e​l​o​p​m​e​n​t​.
	 */
	ABOUTTXT: string
	/**
	 * E​x​p​e​r​i​e​n​c​e​s
	 */
	EXPERIENCES: string
	/**
	 * p​r​e​s​e​n​t
	 */
	PRESENT: string
	/**
	 * P​r​o​j​e​c​t​s
	 */
	PROJECTS: string
	/**
	 * L​a​t​e​s​t​ ​P​o​s​t​s
	 */
	LATEST: string
	/**
	 * R​e​a​d​ ​m​o​r​e​ ​p​o​s​t​s
	 */
	READMORE: string
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	LOADING: string
	/**
	 * M​y​ ​B​l​o​g​s
	 */
	MYBLOG: string
	/**
	 * H​e​r​e​'​s​ ​m​y​ ​b​l​o​g​.​ ​I​ ​w​r​i​t​e​ ​a​b​o​u​t​ ​m​y​ ​p​r​o​j​e​c​t​s​ ​a​n​d​ ​m​y​ ​e​x​p​e​r​i​e​n​c​e​s​.
	 */
	BLOGTXT: string
	/**
	 * B​a​c​k
	 */
	BACK: string
	/**
	 * T​h​e​r​e​'​s​ ​n​o​ ​b​l​o​g​ ​p​o​s​t​ ​y​e​t​.​
​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​b​a​c​k​ ​l​a​t​e​r​ ​o​r​ ​c​h​a​n​g​e​ ​t​h​e​ ​l​a​n​g​u​a​g​e​.
	 */
	BLOG_NOTFOUND: string
	TOOLKIT: {
		/**
		 * W​h​a​t​ ​I​ ​u​s​e
		 */
		USES: string
		/**
		 * M​y​ ​t​o​o​l​k​i​t​ ​t​h​a​t​ ​I​ ​u​s​e​ ​t​o​ ​h​e​l​p​ ​m​e​ ​b​u​i​l​d​ ​m​y​ ​p​r​o​j​e​c​t​s​ ​i​n​ ​b​o​t​h​ ​s​o​f​t​w​a​r​e​ ​a​n​d​ ​h​a​r​d​w​a​r​e​.
		 */
		USESTXT: string
		/**
		 * H​a​r​d​w​a​r​e
		 */
		HARDWARE: string
		HARDWARE_ITEMS: {
			'0': {
				/**
				 * L​a​p​t​o​p​ ​D​e​l​l​ ​l​a​t​i​t​u​d​e​ ​3​5​2​0​ ​(​1​5​.​6​"​,​ ​8​G​B​ ​R​A​M​,​ ​2​5​6​G​B​ ​S​S​D​)
				 */
				NAME: string
				/**
				 * m​y​ ​p​r​i​m​a​r​y​ ​d​e​v​i​c​e
				 */
				DESCRIPTION: string
			}
		}
		/**
		 * S​o​f​t​w​a​r​e
		 */
		SOFTWARE: string
		SOFTWARE_ITEMS: {
			'0': {
				/**
				 * C​u​r​s​o​r
				 */
				NAME: string
				/**
				 * A​I​ ​p​o​w​e​r​e​d​ ​V​S​ ​C​o​d​e​ ​a​l​t​e​r​n​a​t​i​v​e
				 */
				DESCRIPTION: string
			}
			'1': {
				/**
				 * C​h​r​o​m​e
				 */
				NAME: string
				/**
				 * b​e​s​t​ ​b​r​o​w​s​e​r​ ​e​v​e​r
				 */
				DESCRIPTION: string
			}
			'2': {
				/**
				 * P​h​o​t​o​p​e​a
				 */
				NAME: string
				/**
				 * o​n​l​i​n​e​ ​p​h​o​t​o​s​h​o​p​ ​a​l​t​e​r​n​a​t​i​v​e
				 */
				DESCRIPTION: string
			}
			'3': {
				/**
				 * D​r​a​w​.​i​o
				 */
				NAME: string
				/**
				 * o​n​l​i​n​e​ ​d​i​a​g​r​a​m​i​n​g​ ​t​o​o​l
				 */
				DESCRIPTION: string
			}
		}
	}
	/**
	 * E​m​a​i​l
	 */
	EMAIL: string
	/**
	 * C​o​n​t​a​c​t​ ​M​e
	 */
	CONTACTME: string
	/**
	 * Y​o​u​ ​h​a​v​e​ ​a​n​ ​i​d​e​a​ ​o​r​ ​a​ ​p​r​o​j​e​c​t​.​ ​L​e​t​'​s​ ​t​a​l​k​ ​a​b​o​u​t​ ​i​t​,​ ​f​e​e​l​ ​f​r​e​e​ ​t​o​ ​c​o​n​t​a​c​t​ ​m​e​ ​w​i​t​h​ ​m​y​ ​e​m​a​i​l​ ​o​r​ ​s​o​c​i​a​l​ ​m​e​d​i​a​ ​a​c​c​o​u​n​t​.
	 */
	CONTACTTXT: string
}

export type TranslationFunctions = {
	/**
	 * Error
	 */
	ERROR: () => LocalizedString
	/**
	 * Back to Previous Page
	 */
	BACKBUTTON: () => LocalizedString
	/**
	 * Full Stack Web Developer
	 */
	SUBTITLE: () => LocalizedString
	/**
	 * About
	 */
	ABOUT: () => LocalizedString
	/**
	 * Blog
	 */
	BLOG: () => LocalizedString
	/**
	 * Contact
	 */
	CONTACT: () => LocalizedString
	/**
	 * Uses
	 */
	USES: () => LocalizedString
	/**
	 * © 2024 - All Rights Reserved
	 */
	FOOTER: () => LocalizedString
	/**
	 * About Me
	 */
	ABOUTME: () => LocalizedString
	/**
	 * Junior Full Stack Web Developer graduated from the University of M'sila with a license degree in Computer Science. Passionate about creating tools, UI/UX designs and web development.
	 */
	ABOUTTXT: () => LocalizedString
	/**
	 * Experiences
	 */
	EXPERIENCES: () => LocalizedString
	/**
	 * present
	 */
	PRESENT: () => LocalizedString
	/**
	 * Projects
	 */
	PROJECTS: () => LocalizedString
	/**
	 * Latest Posts
	 */
	LATEST: () => LocalizedString
	/**
	 * Read more posts
	 */
	READMORE: () => LocalizedString
	/**
	 * Loading...
	 */
	LOADING: () => LocalizedString
	/**
	 * My Blogs
	 */
	MYBLOG: () => LocalizedString
	/**
	 * Here's my blog. I write about my projects and my experiences.
	 */
	BLOGTXT: () => LocalizedString
	/**
	 * Back
	 */
	BACK: () => LocalizedString
	/**
	 * There's no blog post yet.
 Please check back later or change the language.
	 */
	BLOG_NOTFOUND: () => LocalizedString
	TOOLKIT: {
		/**
		 * What I use
		 */
		USES: () => LocalizedString
		/**
		 * My toolkit that I use to help me build my projects in both software and hardware.
		 */
		USESTXT: () => LocalizedString
		/**
		 * Hardware
		 */
		HARDWARE: () => LocalizedString
		HARDWARE_ITEMS: {
			'0': {
				/**
				 * Laptop Dell latitude 3520 (15.6", 8GB RAM, 256GB SSD)
				 */
				NAME: () => LocalizedString
				/**
				 * my primary device
				 */
				DESCRIPTION: () => LocalizedString
			}
		}
		/**
		 * Software
		 */
		SOFTWARE: () => LocalizedString
		SOFTWARE_ITEMS: {
			'0': {
				/**
				 * Cursor
				 */
				NAME: () => LocalizedString
				/**
				 * AI powered VS Code alternative
				 */
				DESCRIPTION: () => LocalizedString
			}
			'1': {
				/**
				 * Chrome
				 */
				NAME: () => LocalizedString
				/**
				 * best browser ever
				 */
				DESCRIPTION: () => LocalizedString
			}
			'2': {
				/**
				 * Photopea
				 */
				NAME: () => LocalizedString
				/**
				 * online photoshop alternative
				 */
				DESCRIPTION: () => LocalizedString
			}
			'3': {
				/**
				 * Draw.io
				 */
				NAME: () => LocalizedString
				/**
				 * online diagraming tool
				 */
				DESCRIPTION: () => LocalizedString
			}
		}
	}
	/**
	 * Email
	 */
	EMAIL: () => LocalizedString
	/**
	 * Contact Me
	 */
	CONTACTME: () => LocalizedString
	/**
	 * You have an idea or a project. Let's talk about it, feel free to contact me with my email or social media account.
	 */
	CONTACTTXT: () => LocalizedString
}

export type Formatters = {}
